### ISSUE TITLE
Slight visual bug

### ISSUE THREAD

**Issue by SoulSlashMaster** [ReStartQ/anicour#2]
Hello, just want report when a show is over 1000 episode long it doesn't show correctly.
![image](https://github.com/ReStartQ/courier/assets/42787140/37c0c385-01cb-4fb7-ae97-ce1ca222a188)

Great app. Hope to see more updates.

**Comment by ghost** [comment]
detective conan hasn't finished yet nor has a planned episode to end, which is why it shows up as "XXX/?"

**Comment by SoulSlashMaster** [comment]
Sorry if the post was confusing.  I'm at episode 1091 and it only shows 3 digits unless you click on it to move to the end.
![image](https://github.com/ReStartQ/courier/assets/42787140/a4793da3-09b1-45ac-9cd3-e7b726c9c965)
![image](https://github.com/ReStartQ/courier/assets/42787140/6679904e-53b6-4863-a83b-2bc91cd07f00)

**Comment by ReStartQ** [comment]
@SoulSlashMaster Currently in the development process for a complete remake of the app. This won't be an issue in the new app as it is using code that has no relationship to the current repository (UI library, framework, state management, etc...). 

The cards are going to have a much different design than before with features such as a context menu. I have decided on an episode input limit of 100,000. 
Currently still in the process of selecting progress components (input vs text + increment/decrement buttons), but both should completely fit inside the new card with any value below the new limit. 

Can't show a preview of what the list cards will look like as they are still in development, but here is a preview of some of the season cards with the context menu. 
It will look something similar to this but with ways for you to edit your media entry (episodes progress, user score).

![image](https://github.com/ReStartQ/courier/assets/61175330/d66c4e5b-1674-41ca-8011-f4b8705e3e38)
